apiVersion: v1
kind: Service
metadata:
  name: cloudcore
  namespace: kubeedge
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-id: "lb-wz969qjsc58wk42fqfwer" # 阿里云clb 实例id
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-force-override-listeners: "true"
  labels:
    k8s-app: kubeedge
    kubeedge: cloudcore
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 10000
    name: cloudhub
  - port: 10001
    name: cloudhub-quic
  - port: 10002
    name: cloudhub-https
  - port: 10003
    name: cloudstream
  - port: 10004
    name: tunnelport
  selector:
    k8s-app: kubeedge
    kubeedge: cloudcore
  type: LoadBalancer
  externalIPs: # 对外ip
  - 39.108.49.13