apiVersion: v1
kind: Namespace
metadata:
  name: test-hs-ns

---

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: kubernetes-dashboard
  name: kubernetes-dashboard
  namespace: test-hs-ns