---
- hosts: k8s
  gather_facts: no
  vars:
    - k8s_version: 1.22.17
  tasks:
    - name: iptables
      shell:
        cmd: |
          cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
          overlay
          br_netfilter
          EOF
    - name: modprobe
      shell: modprobe overlay && modprobe br_netfilter
    - name: sysctl config
      shell:
        cmd: |
          cat <<EOF | tee /etc/sysctl.d/k8s.conf
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1
          EOF
    - name: start sysctl
      shell: sysctl --system
    - name: lsmod br_netfilter
      shell: lsmod | grep br_netfilter && lsmod | grep overlay
    - name: confi
      shell: sysctl net.bridge.bridge-nf-call-iptables net.bridge.bridge-nf-call-ip6tables net.ipv4.ip_forward
    - name: close firewalld
      service:
        name: firewalld
        state: stopped
        enabled: no
    - name: close swap
      shell: swapoff -a && sed -ri 's/.*swap.*/#&/' /etc/fstab
    - name: install ntpdate
      yum: 
        name:
          - ntpdate
    - name: sync time
      shell: "ntpdate time.windows.com"
    - name: set kubernetes yum repo
      shell:
        cmd: |
          cat <<EOF > /etc/yum.repos.d/kubernetes.repo
          [kubernetes]
          name=Kubernetes
          baseurl=https://mirrors.aliyun.com/kubernetes/yum/repos/kubernetes-el7-x86_64/
          enabled=1
          gpgcheck=1
          repo_gpgcheck=1
          gpgkey=https://mirrors.aliyun.com/kubernetes/yum/doc/yum-key.gpg https://mirrors.aliyun.com/kubernetes/yum/doc/rpm-package-key.gpg
          EOF
    # - name: close selinux
    #   shell: /sbin/setenforce 0
    - name: premanment close selinux
      shell: 
        cmd: | 
          sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
    - name: install kubernetes
      yum:
          name: 
            - kubelet-{{ k8s_version }}
            - kubeadm-{{ k8s_version }}
            - kubectl-{{ k8s_version }}
    - name: start
      shell: systemctl enable --now kubelet && systemctl enable kubelet && systemctl start kubelet