apiVersion: v1
kind: Namespace
metadata:
  name: t-eio-dashboard

---

kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: t-eio-dashboard
  name: t-eio-dashboard
  namespace: t-eio-dashboard
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    k8s-app: t-eio-dashboard
  type: NodePort
  externalIPs:
    - 119.23.226.24
---

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: t-eio-dashboard
  name: t-eio-dashboard
  namespace: t-eio-dashboard
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: t-eio-dashboard
  template:
    metadata:
      labels:
        k8s-app: t-eio-dashboard
    spec:
      nodeSelector: # configure the nodeSelector here to directly schedule pods to specific nodes
        my_app: t-eio
      hostAliases:
        - ip: "120.79.183.159"
          hostnames:
          - "k8s-vip"
      containers:
        - name: t-eio-dashboard-manager
          image: t-eio/ec-manager:v0.0.1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              protocol: TCP
        - name: t-eio-dashboard-web
          image: t-eio/ec-manager-web:v0.0.1
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              protocol: TCP