apiVersion: v1
kind: Namespace
metadata:
  name: nx-yolov5

---

kind: Service
apiVersion: v1
metadata:
  name: nx-yolov5-service
spec:
  selector:
    k8s-app: nx-yolov5
  type: NodePort

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: nx-yolov5-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: nx-yolov5
  template:
    metadata:
      labels:
        k8s-app: nx-yolov5
    spec:
      nodeName: nxtest #指定nx节点部署容器
      containers:
        - name: py-cuda-nx-yolov5
          image: nvcr.io/nvidia/l4t-pytorch:r35.2.1-pth2.0-py3
          imagePullPolicy: Never # 直接从nx本地启动镜像
          env:
          - name: "DISPLAY"
            value: "unix:0"
          args: ["--runtime nvidia"]
          volumeMounts:
          - name: X11-volume
            mountPath: /tmp/.X11-unix
          - name: dev-video0
            mountPath: /dev/video0
          ports:
            - containerPort: 9090
      volumes:
        - name: X11-volume
          hostPath:
            # 宿主上目录位置
            path: /tmp/.X11-unix
             # 此字段为可选
             # type: Directory
        - name: dev-video0
          hostPath:
            # 宿主上目录位置
            path: /dev/video0
            # 此字段为可选
      
