kind: Service
apiVersion: v1
metadata:
  name: deepstream-run-service
spec:
  ports:
    - name: rtsp-port
      port: 8554
      targetPort: 8554
    - name: udp-port
      port: 5400
      targetPort: 5400
  selector:
    app: deepstream-pod-run
  type: NodePort

---

apiVersion: v1
kind: Pod
metadata:
  name: deepstream-pod-run
  labels:
    app: deepstream-pod-run
spec:
  nodeName: admin123-desktop
  containers:
    - name: deepstream-app
      image: haoshuai/deepstream-l4t:6.2
      imagePullPolicy: Never
      ports: 
      - containerPort: 8554
        hostPort: 8554
      - containerPort: 5400
        hostPort: 5400
      volumeMounts:
      - name: dev-video0
        mountPath: /dev/video0
      - name: argus-socket
        mountPath: /tmp/argus_socket
      securityContext:
        privileged: true
  volumes:
    - name: dev-video0
      hostPath:
        path: /dev/video0
    - name: argus-socket
      hostPath:
        path: /tmp/argus_socket