apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: inferences.zh
spec:
  group: zh
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                apiVersion:
                  description: '版本'
                  type: string
                kind: 
                  description: '类型'
                  type: string
                metadata:
                  type: object
                spec:
                  properties: 
                    nodeSelector:
                      description: '模型需要下载的node 标签'
                      type: object
                    nodeName:
                      description: '模型需要下载的node 名称'
                      type: string
                    models:
                      description: '一个节点上存在很多数据模型'
                      items: 
                        properties:
                          model: 
                            description: '模型下载地址'
                            type: string
                          description:
                            description: "模型描述"
                            type: string
                          name:
                            description: '模型名称'
                            type: string
                          type: 
                            description: '模型类型 yolov5 trt tf'
                            type: string
                          path:
                            description: '模型存储路径'
                            type: string
                          sha256sum:
                            description: '模型签名 检验模型的完整性'
                            type: string
                          size:
                            description: '模型大小 单位 字节'
                            type: number
                      type: array
                  required:
                   - nodeSelector
                   - nodeName
                  type: object  
  scope: Namespaced
  names:
    plural: inferences
    singular: inference
    kind: Inference
    shortNames:
     - ifn