apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: inferences.zh.io
spec:
  group: zh.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties: 
                nodeSelector:
                  description: '模型需要下载的node 标签'
                  type: object
                nodeName:
                  description: '模型需要下载的node 名称'
                  type: string
                models:
                  description: '一个节点上存在很多数据模型'
                  items: 
                    type: object
                    properties:
                      replicas:
                        description: '重试次数'
                        type: integer
                      model: 
                        description: '模型下载地址'
                        type: string
                      description:
                        description: "模型描述"
                        type: string
                      name:
                        description: '模型名称'
                        type: string
                      type: 
                        description: '模型类型 yolov5 trt tf'
                        type: string
                      path:
                        description: '模型存储路径'
                        type: string
                      sha256sum:
                        description: '模型签名 检验模型的完整性'
                        type: string
                      size:
                        description: '模型大小 单位 字节'
                        type: integer
                  type: array
            status:
              description: '模型下载的状态情况'
              type: object
              properties:
                startTime : 
                  description: '模型下载状态集合'
                  type: date
                phase:
                  description: '模型下载状态集合'
                  type: string
                  enum: ["Pending", "Succeeded", "Failed", "Unknown"]
                message:
                  description: '处于当前状态的原因'
                  type: string
                # conditions:
                #   description: '模型下载状态集合'
                #   type: array
                #   items:
                #     type: object
                #     properties:
                #       status:
                #         description: "表明该状况是否适用，"
                #         type: string
                #         enum: ["True", "False", "Unknown"]
                #       type: 
                #         description: "状况的名称"
                #         type: string
                #         enum: ["ModelScheduled", "Model", "high"]
                #       message:
                #         description: "人类可读的消息"
                #         type: string
                #       lastTransitionTime:
                #         description: "从上一个状态流转到下一个状态的时间"
                #         type: date
                        
              # required: 表示必须字段
              #  - nodeSelector
              #  - nodeName
              #  - models
                    
  scope: Namespaced
  names:
    plural: inferences
    singular: inference
    kind: Inference
    shortNames:
     - ifn