apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: inferences.zh.io
spec:
  group: zh.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties: 
                nodeSelector:
                  description: '模型需要下载的node 标签'
                  type: object
                nodeName:
                  description: '模型需要下载的node 名称'
                  type: string
                models:
                  description: '一个节点上存在很多数据模型'
                  items: 
                    type: object
                    properties:
                      replicas:
                        description: '重试次数'
                        type: integer
                      model: 
                        description: '模型下载地址'
                        type: string
                      description:
                        description: "模型描述"
                        type: string
                      name:
                        description: '模型名称'
                        type: string
                      type: 
                        description: '模型类型 yolov5 trt tf'
                        type: string
                      path:
                        description: '模型存储路径'
                        type: string
                      sha256sum:
                        description: '模型签名 检验模型的完整性'
                        type: string
                      size:
                        description: '模型大小 单位 字节'
                        type: integer
                  type: array
              # required: 表示必须字段
              #  - nodeSelector
              #  - nodeName
              #  - models
                    
  scope: Namespaced
  names:
    plural: inferences
    singular: inference
    kind: Inference
    shortNames:
     - ifn